### ISSUE TITLE
'user_not_found', 'User with uid was not found. Please check the uid again.'

### ISSUE THREAD

**Issue by fachryluid** [pi-apps/pi-sdk-integration-guide#1]
I'm trying to create a new payment. why am I getting this error? isn't that uid defined by my app?

**Comment by li41** [comment]
+1

**Comment by Alfinace** [comment]
I'm getting error while cal thel endpoint https://api.minepi.com/v2/payments with uid value exact
{
  "error": "user_not_found",
  "error_message": "User with uid  was not found. Please check the uid again."
}

**Comment by abuzaforfagun** [comment]
@fachryluid how did you fix the issue?
I am facing the same error.
